### ISSUE TITLE
How soon is "soon"?

### ISSUE THREAD

**Issue by laubonghaudoi** [google-research-datasets/dialogue#1]
Sounds like a dumb question but just looking forward to the release of codes and data sets.

**Comment by abhirast** [comment]
The dataset needed to be released through LDC because it is based on the ATIS corpus distributed by them. The dataset is now released on the [LDC site](https://catalog.ldc.upenn.edu/LDC2019T04) and the link has been updated on the README. Sorry for the unintentional delay.
